### ISSUE TITLE
Arguments in getNestedObject

### ISSUE THREAD

**Issue by laevilgenius** [flexdinesh/typy#21]
Since `getNestedObject` is an arrow function, `arguments` shouldn't be used here:
https://github.com/flexdinesh/typy/blob/d891dc729994eb92f355da8a94c7b45149b8ebad/src/util.js#L1-L2

**Comment by flexdinesh** [comment]
@laevilgenius Thanks for pointing this out.

This is not exactly a bug but something that needs to be fixed.

**Comment by laevilgenius** [comment]
@flexdinesh it breaks bundling to esm module for me, `arguments` gets hoisted to the top level, and I get `arguments is not defined` error.

**Comment by flexdinesh** [comment]
@laevilgenius Ah I see. We gotta fix this. Wanna create a PR?

**Comment by laevilgenius** [comment]
@flexdinesh, I might. The easiest solution would be just to replace the arrow function with normal function, what do you think?

**Comment by flexdinesh** [comment]
@laevilgenius I think we might skip `arguments` altogether. We could just do

`dotSeparatedKeys && typeof dotSeparatedKeys !== 'string'`

instead of

`arguments.length > 1 && typeof dotSeparatedKeys !== 'string'`

**Comment by flexdinesh** [comment]
Changes published in `v3.3.0`

**Comment by flexdinesh** [comment]
Thanks @laevilgenius
