### ISSUE TITLE
Typings in npm package

### ISSUE THREAD

**Issue by AnthonySLWhite** [flexdinesh/typy#24]
I use the package almost every day but something is annoying me and I'm probably not the only one.

If you use the npm package, there is no typing file supplied and there is no reference to it in the package.json file.

**Comment by flexdinesh** [comment]
@AnthonySLWhite It's a valid case and I should have gotten back to you on this a lot earlier. Apologies for the delay.

Let's get a move on this. How would you like to address this issue? TBH TypeScript is a bit out of my depth. Would you like to open a PR?

**Comment by flexdinesh** [comment]
`v3.2.0` published with TypeScript type definitions 🎉
