### ISSUE TITLE
Small error in documentation

### ISSUE THREAD

**Issue by akarelas-pt** [flexdinesh/typy#6]
In page https://github.com/flexdinesh/typy#safeobject it says:

```
const myObj = t(deepObj, 'nestedArray[1].superNestedKey.superGoodKey').safeObject; // => 'typy is great :)'
```

You should replace `deepObj` with `anotherDeepObj` to be correct.

**Comment by flexdinesh** [comment]
Thanks @akarelas-pt. This is fixed as part of commit 0dd559556205c7f4a1b851402921951d98fe249f.
